import type { NextPage } from 'next';
import Head from 'next/head';
import Footer from '../components/footer';
import Toolbar from '../components/toolbar';
import { HomeContainer, Main } from '../styles/pages/Home';

const Home: NextPage = () => {
  return (
    <HomeContainer>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toolbar />
      <Main>
        <h1>
          Fruit Salad
        </h1>
      </Main>
      <Footer></Footer>
    </HomeContainer>
  );
};

export default Home;
